blank_issues_enabled: false
contact_links:
  - name: Questions about Smith
    url: https://github.com/Smithhss/smithhs.github.io/discussions
    about: 一些使用问题请到 Discussion 询问。 Please ask questions in Discussion.
